apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml

commonLabels:
  component: database
  
images:
- name: mysql
  newTag: "8.0"