apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  database-name: "appdb"
  charset: "utf8mb4"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3JkMTIz  # rootpassword123 base64 encoded
  username: YXBwdXNlcg==  # appuser base64 encoded
  password: cGFzc3dvcmQxMjM=  # password123 base64 encodeddb/base/kustomization.yaml