apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch.yaml

configMapGenerator:
- name: mysql-config
  behavior: merge
  literals:
  - database-name=appdb_prod
  - charset=utf8mb4

secretGenerator:
- name: mysql-secret
  behavior: merge
  literals:
  - root-password=prodrootpass456
  - username=produser
  - password=prodpass456

images:
- name: mysql
  newTag: "8.0"