apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../app/overlays/prod
- ../../db/overlays/prod

namespace: prod
namePrefix: prod-

commonLabels:
  environment: production
  managed-by: kustomize
  
commonAnnotations:
  environment: "production"
  team: "team4"