apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../app/overlays/dev
- ../../db/overlays/dev

namespace: dev
namePrefix: dev-

commonLabels:
  environment: development
  managed-by: kustomize
  
commonAnnotations:
  environment: "development"
  team: "team4"